name: lake-mead
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - scipy
  - statsmodels
  - patsy
  - seaborn      
  - pip
  - pip:
      - openpyxl
      - requests
